server:
  port: 8088

spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 990915
    url: jdbc:mysql://localhost:3306/news?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
  rabbitmq:
    host: 116.62.6.60
    username: ZY
    password: 990915
    virtual-host: news
    #确认消息已经发送到交换机
    publisher-confirms: true
    #确认消息已经到队列
    publisher-returns: true
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


news:
  zzy:
    allowHeadKeys:
      - T-KEY: news-zzy
        T-SEC: 99b2eeecb4f10339


